# Config file for automatic testing at travis-ci.org

language: python
dist: xenial
python:
  - 3.7

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc

stages:
  - name: migrate
    if: branch IN (master,feature)

jobs:
  include:
    - stage: migrate
      script:
        - docker-compose up -d --scale kafka=3


